GET http://localhost:3001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTI4NTE4MjQsImV4cCI6MTYxMjg1MTgzOSwiYXVkIjoiNjAyMjIxNzdhOTRhZTU1YTJmM2EwOGMzIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.EN6dV7ogGpsWM-knxJgkvTv5VrKd2BmUwrw7BLBnOOI
###

GET http://localhost:3001/325983

###

POST http://localhost:3001/auth/login

###

POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "email":"duynv1895@gmail.com",
    "password":"duy123456"
    
}
###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email":"duynv1895@gmail.com",
    "password": "duy123456"
}
